### ISSUE TITLE
Output save file

### ISSUE THREAD

**Issue by tiagodscosta** [NewcastleRSE/Java_taVNS#5]
This might be in part me just not understanding what I’m looking at.

Regardless, just some things in my mind:
- Appears to be in “wide” format, could it be in “long” format?
- Would be nice to have some labels, for the future – not clear what we are recording
- Wonder if we could have something like:
. Column 1: type stamp - whatever works with appropriate resolution, unix epoch fine.
. Column 2: breathing plot value
. Column 3: stim plot value
. Column 4: stim mode (on fall, on rise, etc)
. Column 5: Amplitude delivered
. Etc - basically, just a way to have all settings on output

**Comment by jsteyn** [comment]
File changed to wide format

**Comment by jsteyn** [comment]
Titles of charts can be changed in the GUI by right clicking on the title. Those title are now used as column headings when the data is saved.
